* Which Marvel Character Are You App

** TDD?
+ Set it up, but may not use it?

** Requirements (user-stories)

*** Bare-Minimum Requirements

+ I open the app, and I see a title 'Which Marvel Character Are You?' with a picture of one or several Marvel Charcters beneath it.
+ Big ol' button that says "Start the quiz!"

+ When I click the button, the button dissapears and the first question appears with multiple (four?) answers to choose from beneath it.
+ Beneath the answers, 'previous' and 'next' button.
    - If this is the first question, the 'previous' button should not appear.
    - If this is the last question, the 'next' button should be replaced with a 'Submit your quiz' button

+ When I his the 'Submit my quiz' button, a picture of a Marvel character with the words 'You are [character name here]!' should appear with a description on why that character was chosen somewhere on the page.
+ Below the results should be a 'Take the quiz again?' button, which starts the quiz all over, starting from the first question.

*** Other Requirements

+ Single page
+ Should be images on the 'questions' pages, as well as on some of the answers.

** Example Questions:

+ If you could choose one power, which one would it be?
  - Super Strength //captain
  - Invisibility 
  - Flying
  - Super Intelligence
  - Form Changing  

+ If your friends described you in one word, what would it be?
  - Humble
  - Devious
  - Adventurous
  - Witty

+ Who would you choose as a sidekick (pictures)?
  - War Machine
  - Winter Soilder
  - Hawkeye
  - Loki


  ----------
  Black Widow  -- Super Spy -- 1009189
  Captain America -- Super Soldier -- 1009220
  Iron Man -- Super Genius -- 1009368
  Hulk -- Super Smash -- 1009351
  Hawk Eye -- Super Aim -- 1009338
  Thor -- Super Hair -- 1009664

** API

+ https://developer.marvel.com/
+ Public key: 57a9282eee09f642116d68d165ec7808

* To-Do
+ How do we implement each question? // DONE
 - Do we make a page each question? //DONE
 - Make a file, write questions /w answers, and pull from that file //DONE

+ What are our possible characters? // DONE (The Avengers)
+ How do we arrive at a character?  // DONE 

+ How do we save the answers that are chosen? // DONE

+ Getting a result from our answers // DONE
+ Create a results page // IN PROGRESS

+ How to actually pull from the API, and what are we pulling? 

http://gateway.marvel.com/v1/public/characters?ts=1&apikey=57a9282eee09f642116d68d165ec7808&hash=a0bf7203d0c30c222375c89f716f66be
